#!/usr/bin/env sh

SESSION=" FastAPI"
SESSIONEXISTS=$(tmux list-sessions | grep "$SESSION")

if [ "$SESSIONEXISTS" = "" ]; then
    tmux new-session -d -s "$SESSION"

    tmux rename-window -t "$SESSION" 'shell'
    tmux send-keys -t 'shell' 'clear' C-m

    tmux new-window -t "$SESSION" -n 'vim'
    tmux send-keys -t 'vim' 'vim' C-m ':CocCommand explorer' C-m
    tmux split-window -h -p 20 'make run-local'
    tmux select-pane -t 0

    tmux new-window -t "$SESSION" -n 'git'
    tmux send-keys -t 'git' 'lazygit' C-m

    tmux new-window -t "$SESSION" -n 'repl'
    tmux send-keys -t 'repl' 'python3' C-m
fi

tmux attach-session -t "$SESSION"
