#!/usr/bin/env sh

export PATH="$PATH:$SONAR_SCANNER_HOME/bin"
export PATH="$PATH:$(du "$HOME/.scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export PATH=~/.npm-global/bin:"$PATH"
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$PATH:/home/ges/.dotnet/tools"
