#!/usr/bin/env sh

PATH="$PATH:$SONAR_SCANNER_HOME/bin"
PATH="$PATH:$(du "$HOME/.scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
PATH="$PATH:$HOME/.npm-global/bin"
PATH="$PATH:$HOME/bin:/usr/local/bin"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:/home/ges/.dotnet/tools"
export PATH
