#!/usr/bin/env sh

progress () {
    echo -e -n " $1\r"
}

completed () {
    echo -e -n " $1\n"
}

progress "Setting env vars"
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
COUNT=0
FILE_CNT=$(find lib ! -path lib -type f | wc -l)
completed

progress "Making directories"
# Required paths for vim and mpd
mkdir -p ~/.vim/tmp/undo
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap
mkdir -p ~/.config/mpd/res
mkdir -p ~/.config/mpd/res/playlists
touch ~/.config/mpd/log
completed " Making directories"

# Symlink and backup all files in ./lib
find lib ! -path lib -type f | while read FILE; do
    FILE=${FILE:4}
    DIR=$(dirname "$HOME/$FILE")
    BACKUPFILE="$SCRIPTPATH/back/$FILE"
    BACKUPDIR=$(dirname "$SCRIPTPATH/back/$FILE")

    mkdir -p "$DIR"
    mkdir -p "$BACKUPDIR"

    if [ -f "$HOME/$FILE" ]; then
        cp "$HOME/$FILE" "$BACKUPFILE"
        rm "$HOME/$FILE"
    fi

    ln -s -f "$SCRIPTPATH/lib/$FILE" "$HOME/$FILE" 2>&1 >/dev/null
    ((COUNT++))
    progress "Updated $COUNT/$FILE_CNT symlinks"
done
completed "Updated $COUNT/$FILE_CNT symlinks"

progress "Setup vim plug"
[[ -f ~/.vim/autoload/plug.vim ]] || curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
[[ -f ~/.local/share/nvim/site/autoload/plug.vim ]] || curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
completed "Setup vim plug"

progress "Setup oh-my-zsh"
[[ -d ~/.config/.oh-my-zsh ]] || sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
[[ -d ~/.config/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]] || git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/.oh-my-zsh/custom/plugins/zsh-autosuggestions
[[ -d ~/.config/.oh-my-zsh/custom/plugins/zsh-completions ]] || git clone https://github.com/zsh-users/zsh-completions ~/.config/.oh-my-zsh/custom/plugins/zsh-completions
[[ -d ~/.config/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]] || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

completed "Setup Oh-my-zsh"

# VIM & NVIM plugins
/usr/bin/vim +PlugInstall +PlugClean +qall
/usr/bin/nvim +PlugInstall +PlugClean +qall

# Update font cache.
fc-cache

# Setup user services.
systemctl enable --user synccal.timer
systemctl restart --user synccal.timer
systemctl enable --user sync_music.timer
systemctl restart --user sync_music.timer
systemctl enable --user mpd.service
systemctl restart --user mpd.service
systemctl enable --user bing-wallpaper.service
systemctl restart --user bing-wallpaper.service
systemctl enable --user mbsync.timer
systemctl restart --user mbsync.timer

# Refresh DWM bar.
#refdwmbar

# Rebuild DWM.
#cd $HOME/doc/src/github.com/kruhlmann/dwm/
#git pull
#git add .
#git commit -am "Updated through dotfiles (https://github.com/Kruhlmann/dotfiles)"
#git push
#sudo make install

# Rebuild and restart Xmonad.
xmonad --recompile; xmonad --restart
