#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
FILES=$(find lib ! -path lib -type f)
COUNT=0

for LIBFILE in $FILES; do
    FILE=${LIBFILE:4}
    DIR=$(dirname "$HOME/$FILE")
    BACKUPFILE="$SCRIPTPATH/back/$FILE"
    BACKUPDIR=$(dirname "$SCRIPTPATH/back/$FILE")

    mkdir -p "$DIR"
    mkdir -p "$BACKUPDIR"

    if [ -f "$HOME/$FILE" ]; then
        cp "$HOME/$FILE" "$BACKUPFILE"
        rm "$HOME/$FILE"
    fi

    ln -s -f "$SCRIPTPATH/lib/$FILE" "$HOME/$FILE" 2>&1 >/dev/null
    ((COUNT++))
done
echo -e "\e[36mUpdated $COUNT files.\e[0m"
