#!/usr/bin/env sh

MAC_ADDRESS="$1"
PROFILE=$(audio_profile_from_mac "$MAC_ADDRESS")

[ -z "$PROFILE" ] && exit 1

if [ "$PROFILE" = "headset_head_unit" ]; then
    echo %{F#458588}%{F-}""
else
    echo %{F#555555}%{F-}""
fi

