#!/usr/bin/env sh

YEAR=$(date +%Y)
WEEKNUMBER=$(($(date +%W) + 1))
WEEKDAY=$(($(date +%w) - 1))

download_file()
{
    # download_file week_number year
    # download_file 47 2020
    curl -s "https://sreballerup.iss.dk/api/v1/iss-menu-plan/menus/$1/$2/lunch" > "$HOME/.cache/canteen_w$1_$2"
}

if [ ! -f "$HOME/.cache/canteen_w${WEEKNUMBER}_${YEAR}" ] ; then
    download_file "${WEEKNUMBER}" "${YEAR}"
elif [ "$(stat -c %y "$HOME/.cache/canteen_w${WEEKNUMBER}_${YEAR}" |
        xargs -0 date +"%Y-%m-%d" -d)" != "$(date '+%Y-%m-%d')" ] ; then
    download_file "${WEEKNUMBER}" "${YEAR}"
fi
jq -r --arg WEEKDAY $WEEKDAY '.data | .attributes | .daily_menus[$WEEKDAY|tonumber] | .menu_items[0] | .name' < "$HOME/.cache/canteen_w${WEEKNUMBER}_${YEAR}"
