#!/usr/bin/env sh

$HOME/.scripts/refdwmbar

while :; do
    mkdir $HOME/.cache/dwmbar/
    xsetroot -name "                             $(cat $HOME/.cache/dwmbar/top_* | tr '\n' ' ');$(cat $HOME/.cache/dwmbar/bot_* | tr '\n' ' ')"
    sleep 0.1s
done
