#!/bin/sh

TOKEN="$HOME/.cache/gitlab-token"
CACHE_FILE="$HOME/.cache/gitlab_merge_requests"
BASE_DOMAIN=https://mo-gitlab.siemens.dk

download_file()
{ 
    curl -s "${BASE_DOMAIN}/api/v4/merge_requests?private_token=${TOKEN}&state=opened" | \
        jq > "$CACHE_FILE"
}

if [ ! -f "${CACHE_FILE}" ] ; then
    download_file
elif [ $(stat -c %Y "${CACHE_FILE}") -lt $(($(date +"%s")-180)) ] ; then 
    download_file
fi

OUTPUT="$(cat "${CACHE_FILE}" | jq 'map(.reviewers) | .[] | .[] | select(.username == "ASK") | .id' | wc -l)"
echo "$OUTPUT"
