#!/usr/bin/env sh

TOKEN="$(cat "$HOME/.cache/gitlab-access-token")"
GL_HOST="$(jq <"$HOME/.cache/siemens-config.json" '.gitlab_host')"

project_json=$(curl -s --header "PRIVATE-TOKEN: $TOKEN" "https://$GL_HOST/api/v4/projects/$1")
path=$(echo "$project_json" | jq --raw-output '.path_with_namespace')
clone_url=$(echo "$project_json" | jq --raw-output '.ssh_url_to_repo')
destination="$HOME/doc/src/$GL_HOST/$path"

git clone "$clone_url" "$destination"
