#!/usr/bin/env sh

relevant_issues=$(~/.scripts/gitlab/issues | jq --raw-output '[.[] | select((.web_url | startswith("https://mo-gitlab.siemens.dk/sw-group/banedanmark/s-bane/pykpi")) and (.labels[] | contains ("In Sprint")))]')
open=$(echo "$relevant_issues" | jq --raw-output '[.[] | select(.state == "opened").time_stats.time_estimate] | add')
closed=$(echo "$relevant_issues" | jq --raw-output '[.[] | select(.state == "closed").time_stats.time_estimate] | add')
total=$((open + closed))
echo "$((closed * 100 / total))% $((closed / 3600))/$((total / 3600))"
