#!/bin/sh

B='#00000077'  # blank
C='#ffffff99'  # clear ish
D='#77777799'  # default
S='#44444499'  # darker default
T='#ffffff99'  # text
W='#66000099'  # wrong
V='#eeeeee99'  # verifying

i3lock \
--insidevercolor=$B   \
--ringvercolor=$V     \
\
--insidewrongcolor=$B \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$S       \
--bshlcolor=$S        \
\
--screen 1            \
--blur 15              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--keylayout 1         \
-e                    \
--veriftext="Stand by..." \
--wrongtext="Access denied" \
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
