#!/usr/bin/env sh

FILE_PATH=$1
FILENAME=$(basename "$FILE_PATH")

mkdir -p $FILE_PATH

cat << EOT >> "$FILE_PATH/$FILENAME.svelte"
<script context="module">

</script>

<script src="./$FILENAME.js">

</script>

<template lang="pug" src="./$FILENAME.pug"></template>


<style lang="scss">
    @import "$FILENAME";
</style>
EOT

touch "$FILE_PATH/$FILENAME.scss"
touch "$FILE_PATH/$FILENAME.ts"
touch "$FILE_PATH/$FILENAME.pug"

echo "Created $FILE_PATH/$FILENAME.svelte"
echo "Created $FILE_PATH/$FILENAME.scss"
echo "Created $FILE_PATH/$FILENAME.ts"
echo "Created $FILE_PATH/$FILENAME.pug"
