#!/usr/bin/env sh

DEST_DIR="$1"

URL=$(curl "https://api.nasa.gov/planetary/apod?api_key=$NASA_API_KEY" | jq -r .hdurl)
FNAME=$(echo "$URL" | xargs -L 1 basename)
FINAL_PATH="$DEST_DIR/$FNAME"

mkdir -p "$DEST_DIR"

if [ ! -f "$FINAL_PATH" ]; then
    curl "$URL" -o "$FINAL_PATH"
    feh --bg-scale "$FINAL_PATH"
fi
