#!/usr/bin/env sh
echo -n "%{F#458588}%{F-}"
calcurse -n | sed -e 's/next appointment\://g' | tr '\n' ' ' | xargs | awk -v len=40 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }'
