#!/usr/bin/env sh

RESET_COLOR="%{F-}"
WARN_COLOR="%{F#AA7700}"
DEFAULT_COLOR="%{F#458588}"
HEADSET_ICO=""

LOGITECH_BATTERY=$(sudo headsetcontrol -b | tail -n 1 | grep -oE '[0-9]+')

if [ $LOGITECH_BATTERY -gt 30 ]; then
    echo "$DEFAULT_COLOR$HEADSET_ICO$RESET_COLOR $LOGITECH_BATTERY%"
elif [ $LOGITECH_BATTERY -gt 0 ]; then
    echo "$WARN_COLOR$HEADSET_ICO$RESET_COLOR $LOGITECH_BATTERY%"
fi



#BEGIN {
    #"command -v headsetcontrol >/dev/null 2>&1; echo $?" | getline use_headsetcontrol

    #if (use_headsetcontrol == "0") {
        #while ("sudo headsetcontrol -b" | getline headsetcontrol_line > 0) {
            #if (headsetcontrol_line ~ /Battery: [0-9]{1,3}%/) {
                 #match(headsetcontrol_line, / .../, headsetcontrol_battery)
                #print substr(headsetcontrol_battery[0], RSTART, RLENGTH)
                ##print "%{F#458588}%{F-} "
            #}
        #}
    #}
#}


