#!/usr/bin/env sh

curl -sL 'https://www.astma-allergi.dk/umbraco/Api/PollenApi/GetPollenFeed' | node -e 'const fs=require("fs");const b=fs.readFileSync(0);console.log(b.toString().replace(/\\/g, "").slice(1,-1))' | jq '."48".data."28".level'
