#!/usr/bin/env sh

set -ex

build_dir=$(mktemp -d)
git clone git@github.com:neovim/neovim.git "$build_dir"
cd "$build_dir" || exit 1
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
rm -rf "$build_dir"
notify-send \
	-i /usr/share/icons/Papirus/48x48/apps/io.neovim.nvim.svg \
	'Installed neovim' \
	"$(nvim --version | head -n 1 | sed 's/NVIM //')"
