#!/usr/bin/env sh

[ -z "$1" ] && exit 1

search_folder=$1
repositories=$(find ~/doc/src -name .git -type d -prune | sed -e "s|$search_folder||" -e 's/\/\.git//')
selected_repository=$(echo "$repositories" | rofi -dmenu)
repository_directory="$search_folder/$selected_repository"
$TERMINAL -d "$repository_directory"
