#!/usr/bin/env python3

import fileinput
import random

chars = {
        "a": "åä",
        "A": "ÅÄ",
        "e": "ë",
        "E": "Ë",
        "o": "ö",
        "O": "Ö",
}

res = ""
for l in fileinput.input():
    for c in l:
        if c in chars and bool(random.getrandbits(1)):
            c = random.choice(chars[c])
        res += c
    print(res)
    res = ""
