#!/usr/bin/env bash

cd "$HOME/.calcurse"
git remote update

if [[ `git rev-list HEAD...origin/master --count` != 0 ]] ; then
    git pull origin master
    notify-send "Calendar pulled" -i ~/.calcurse/notify-splash.png  
fi
if [[ `git status --porcelain --untracked-files=no` ]]; then
    git add .
    git commit -am "Updated calendar"
    git push -u origin master
    notify-send "Calendar pushed" -i ~/.calcurse/notify-splash.png  
fi

