#!/usr/bin/env sh

RES=""

CPU_TEMP=$(sensors | grep "Package id 0" | xargs | awk '{print $4}' | sed 's/\+//' | sed 's/\..//')
RES="$RES$CPU_TEMP"

if command -v nvidia-smi >/dev/null; then
    GPU_TEMP=$(nvidia-smi | grep -oE '\| [0-9]{1,3}\%   [0-9]{1,4}C' | awk '{ gsub("C", "°C", $3); print $3 }')
    RES="$RES / $GPU_TEMP"
fi

echo "%{F#458588}%{F-} $RES"
