#!/usr/bin/env python3

import sys

for line in sys.stdin:
    line = line.replace("☀", "")
    line = line.replace("☁️", "")
    line = line.replace("⛅️", "")
    line = line.replace("⛈", "")
    line = line.replace("✨", "")
    line = line.replace("🌫", "")
    line = line.replace("🌩","朗")
    line = line.replace("❄️", "")
    line = line.replace("🌨", "")
    line = line.replace("🌧", "")
    line = line.replace("🌦", "")
    if len(sys.argv) > 2 and sys.argv[1] == "--color":
        print("%%{F%s}%s %%{F-} %s" % (sys.argv[2], line[0], line[3:]))
    else:
        print(line)

