#!/usr/bin/env sh

mkdir -p ~/.cache
touch ~/.cache/unread_mail
RES=""
while read LINE; do
    ACC=$(echo $LINE | sed 's/=/ /' | awk '{print $1}')
    ICO=$(echo $LINE | sed 's/=/ /' | awk '{print $2}')
    CNT=$(du -a --exclude="All\ Mail*" ~/mail/$ACC/*/new 2>/dev/null | grep -v "\/new$" | sed -n '$=' | tr -d '\n' | sed 's/^$/0/')
    if [ -z "$CNT" ]; then
      CNT=0 
    fi
    RES="$RES %{F#458588}$ICO%{F-} $CNT"
    PRE=$(cat ~/.cache/unread_mail)
    if [ -z "$PRE" ]; then
      PRE=0 
    fi
    if [ $PRE -lt $CNT ]; then
        notify-send "Unread mail" "You have $CNT unread mails"
        echo $CNT > ~/.cache/unread_mail
    fi
done < ~/.config/mailicons
echo $RES | cut -c 1-
