export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"
export BROWSER="brave"
export NVM_DIR="$HOME/.nvm"
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export DOTFILES="$HOME/Documents/src/dotfiles/lib"
export TERMINAL="termite"
export SHELL="zsh"
export TERM=xterm-color
export NVM_DIR="$HOME/.nvm"
export I3CONFIG=""~/.config/i3/config"
