so ~/.config/nvim/includes/plugins/vim-latex-live-preview.vim
so ~/.config/nvim/includes/plugins/goyo.vim
so ~/.config/nvim/includes/plugins/rainbow_parentheses.vim
so ~/.config/nvim/includes/plugins/indentline.vim
"so ~/.config/nvim/includes/plugins/nvim-lsp.vim
"so ~/.config/nvim/includes/plugins/statusline.vim
so ~/.config/nvim/includes/plugins/coc.vim
so ~/.config/nvim/includes/plugins/vim-clang-format.vim
so ~/.config/nvim/includes/plugins/markdown-preview.vim
so ~/.config/nvim/includes/plugins/vim-which-key.vim
so ~/.config/nvim/includes/plugins/ranger.vim
