so ~/.config/nvim/includes/plugins/nerdtree.vim
so ~/.config/nvim/includes/plugins/leaderf.vim
so ~/.config/nvim/includes/plugins/vim-latex-live-preview.vim
so ~/.config/nvim/includes/plugins/goyo.vim
so ~/.config/nvim/includes/plugins/nerd-commenter.vim
so ~/.config/nvim/includes/plugins/rainbow_parentheses.vim
so ~/.config/nvim/includes/plugins/pathfinder.vim
so ~/.config/nvim/includes/plugins/indentline.vim
so ~/.config/nvim/includes/plugins/vimspector.vim
"so ~/.config/nvim/includes/plugins/nvim-lsp.vim
"so ~/.config/nvim/includes/plugins/statusline.vim
so ~/.config/nvim/includes/plugins/coc.vim
