#!/usr/bin/env sh
# Give a battery name (e.g. BAT0) as an argument.

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "Battery module" "Battery discharging
Not charging
Stagnant charge
Battery charging
Battery charged
Critical battery level
- Text color reflects charge left" ;;
esac



capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 75 ]; then
	warn="❗"
	capcolor="#00ff33"
elif [ "$capacity" -ge 50 ]; then
	capcolor="#ffffff"
elif [ "$capacity" -ge 25 ]; then
	capcolor="#ffff00"
else
	capcolor="#ff0000"
	warn="❗"
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#00ff33"

printf "<span color='%s'>%s </span><span color='%s'>%s</span>\n" "$color" "$status"  "$capcolor" "$(echo "$capacity" | sed -e 's/$/%/')"
