#!/bin/bash

weekday="$(date '+%A')"
month="$(date '+%B')"
arg="+${weekday^} %d. ${month^} %Y %H:%M"
date "$arg"

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "Appointments" "$(calcurse -D ~/.config/calcurse -d 3)" ;;
	3) $TERMINAL -e calcurse -D ~/.config/calcurse ;;
esac
