#!/usr/bin/env sh

filter() {
	sed "/^volume:/d" | tac | sed -e "s/\\&/&amp;/g;s/\\[paused\\].*/<span color=\"gray\" font_style=\"italic\"> /g;s/\\[playing\\].*/<span> /g" | tr -d '\n' | sed -e "s/$/<\\/span>\n/g" | sed -e "s/\.mp3$//"
	}

case $BLOCK_BUTTON in
    1) mpc status | filter && setsid "$TERMINAL" -e ncmpcpp & ;;  # right click, pause/unpause
    3) mpc toggle | filter ;;  # right click, pause/unpause
    4) mpc prev   | filter ;;  # scroll up, previous
    5) mpc next   | filter ;;  # scroll down, next
    *) mpc status | filter ;;
esac; exit
