#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇 <span color='gray'>MUTE</span>\\n" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

if [ "$vol" -lt 100 ]; then
    $vol = " $vol";
fi

if [ "$vol" -lt 10 ]; then
    $vol = " $vol";
fi


printf "%s %s%%\\n" "$icon" "$vol"
