Guidelime.registerGuide(
[[
[GA Alliance]
[N18-20 DM,Redridge Mountains]
[NX20-24Ashenvale,Duskwood]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
If youre NOT in a 5man grp(or cant find ppl for Deadmines) continue with: "Set your hearthstone to GOLDSHIRE"
Accept: [QA2040]
Accept: [QA167]
Set your [H] to Stormwind City at [G52.6,65.7Stormwind City]
Fly to Westfall
Grind in Deadmines till level 21
Accept: [QA373]
TurnIn: [QT373]
TurnIn: [QT2040]
TurnIn: [QT167]
Set your [H] to Elwynn Forest at [G43.8,65.8Elwynn Forest]
Accept: [QA244]
TurnIn: [QT244]
Accept: [QA246]
Get the [P] flightpath at: [G30.6,59.4Redridge Mountains]
Accept: [QA20]
Accept: [QA125]
Accept: [QA118]
Accept: [QA169][O]
Accept: [QA145]
Accept: [QA120]
Accept: [QA91]
Accept: [QA3741]
Accept: [QA180]
Accept: [QA129]
Do: [QC3741]
Kill as many Mongrels as you can at [G17,65]
TurnIn: [QT129]
Accept: [QA130]
Do: [QC246]
Do: [QC125]
Do: [QC20]
Use your [H] Hearthstone.
TurnIn: [QT118]
Accept: [QA119]
TurnIn: [QT120]
Accept: [QA121]
Fly to Redridge Mountains
TurnIn: [QT246]
TurnIn: [QT20]
Accept: [QA19][O]
Accept: [QA115][O]
TurnIn: [QT125]
Accept: [QA89]
TurnIn: [QT119]
Accept: [QA124]
TurnIn: [QT3741]
TurnIn: [QT121]
Accept: [QA386][O]
TurnIn: [QT130]
Accept: [QA131]
TurnIn: [QT131]
Do [QC124- ][QC89 A Baying of Gnolls,The Everstill Bridge]
Grind till [XP19]
TurnIn: [QT89]
TurnIn: [QT124]
(Whenever you can)Do: [QC115]
(Whenever you can)Do: [QC19]
(Whenever you can)Do: [QC169]
TurnIn: [QT19][O]
TurnIn: [QT115][O]
TurnIn: [QT169][O]
Set your [H] to Redridge Mountains at [G26.8,44.6Redridge Mountains]
Fly to Stormwind City
Learn new abilities
Fly to Wetlands
TurnIn: [QT942]
Take the boat to Auberdine.
]], "TUGs The Ultimate (Leveling) Guides")