name: Build & Verify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: arch-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dotfiles
      run: |
          sh ./setup
