name: Build & Verify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kruhlmann/dotfiles
    - name: Install dotfiles
      run: echo 1
