name: Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kruhlmann/dotfiles@3a00a2fea7632168f75277abb2888198e7bf9d89
    - name: Install dotfiles
      run: echo 1
